# Generated by Django 4.2.8 on 2024-02-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0002_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="Password",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
