# Generated by Django 4.2.8 on 2024-02-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0003_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="generate_password",
            field=models.BooleanField(default=False),
        ),
    ]
