# Generated by Django 4.2.8 on 2024-02-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0005_alter_site_generate_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="password",
            name="generate_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="site",
            name="generate_password",
            field=models.BooleanField(default=False),
        ),
    ]
